classDiagram

BaseBlock <|.. StartBlock : Implementation
BaseBlock <|.. ChanceBlock : Implementation
BaseBlock <|.. PrisonBlock : Implementation
BaseBlock <|.. FestivalBlock : Implementation
BaseBlock <|.. TravelingBlock : Implementation
BaseBlock <|.. TaxBlock : Implementation
BaseBlock <|-- BuildableBlock : Implementation
BaseBlock .. BlockLine : Association
BaseBlock .. BlockType : Association

BuildableBlock .. BlockColor : Association
BuildableBlock .. PropertyType : Association
BuildableBlock .. BuildingEffect : Association

BuildableBlock <|.. CityBlock : Implementation
BuildableBlock <|.. TouristBlock : Implementation

namespace Block {
    class BaseBlock{
        <<abstract>>
        + ~readonly~ Id : int
        + ~readonly~ Position : int
        + ~readonly~ Line : BlockLine
        + ~readonly~ Type : BlockType

        + BlockAction(GameController game)*
    }

    class BuildableBlock{
        <<abstract>>
        + ~readonly~ BlockColor : BlockColor
        + ~readonly~ BasePrice : int
        + OwnerId : int
        + PropertyStatus : PropertyType 
        + BuildingEffect : BuildingEffect
        + EffectCount : int


        + GetPropertyRent() : int
        + Sell() : int
        + Buy(IPlayer player, PropertyType type)
        + SetEffect(BuildingEffect effect)
    }


    class CityBlock{
        - _isColorCompletion : bool
        
        + CityBlock(int pos, BlockColor color, int price)
        + BlockAction(GameController game)
        + UpgradeProperty(PropertyType p)
        + AquireCity(IPlayer p)
    }   
    
    class TouristBlock{
        - _countSameColor : int

        + TouristBlock(int pos, BlockColor color, int price)
        + BlockAction(GameController game)
        + GetPropertyRent() : int
    }

    class StartBlock{
        - ~readonly~ _salary : int

        + StartBlock(int salary)
        + BlockAction(GameController game)
    }

    class ChanceBlock{
        - _listOfCard : List<BaseChanceCard>

        + ChanceBlock(int pos)
        + BlockAction(GameController game)
        - GetRandomCard() : BaseChanceCard
    } 

    class PrisonBlock{
        + PrisonBlock(int pos)
        %% choice method : get double dice or pay fee
        + BlockAction(GameController game, int choice)
    }

    class FestivalBlock{
        + BlockAction(GameController game, BuildableBlock building)
    }

    class TravelingBlock{
        + BlockAction(GameController game, BuildableBlock building)
    }

    class TaxBlock{
        + BlockAction(GameController game)
    }
     
}

BaseChanceCard <|.. StormCard : Implementation
BaseChanceCard <|.. BlackoutCard : Implementation
BaseChanceCard <|.. TornadoCard : Implementation
BaseChanceCard <|.. StealCard : Implementation
BaseChanceCard <|.. FreeChargeCard : Implementation
BaseChanceCard <|.. FreeTaxCard : Implementation
BaseChanceCard <|.. EscapeCard : Implementation
BaseChanceCard <|.. GoTaxCard : Implementation
BaseChanceCard <|.. GoStartCard : Implementation
BaseChanceCard <|.. GoTravelingCard : Implementation
BaseChanceCard <|.. RipOffCard : Implementation

IDeffenseCard <|.. FreeChargeCard : Implementation
IDeffenseCard <|.. FreeTaxCard : Implementation
IDeffenseCard <|.. EscapeCard : Implementation
ChanceCardType .. BaseChanceCard : Association
namespace ChanceCard{
    class BaseChanceCard{
        <<abstract>>
        + ~readonly~ Type : ChanceCardType

        + ChanceAction(GameController game)*
    }
    class IDeffenseCard{
        <<interface>>

        + UseCard(IPlayer player)
    }

    %% Attack Card
    class StormCard{
        + StormCard() 
        + ChanceAction(GameController game, BuildableBlock building)
    }
    class BlackoutCard{
        + BlackoutCard()
        + ChanceAction(GameController game, BuildableBlock building)
    }
    class TornadoCard{
        + TornadoCard()
        + ChanceAction(GameController game, BuildableBlock building)
    }
    class StealCard{
        + StealCard()
        + ChanceAction(GameController game, BuildableBlock building)
    }
    
    %% Deffense Card
    class FreeChargeCard{
        + FreeChargeCard()
        + ChanceAction(GameController game)
    }
    class FreeTaxCard{
        + FreeTaxCard()
        + ChanceAction(GameController game)
    }
    class EscapeCard{
        + EscapeCard()
        + ChanceAction(GameController game)
    }

    %% Command Card
    class GoTaxCard{
        + GoTaxCard()
        + ChanceAction(GameController game)
    }
    class GoStartCard{
        + GoStartCard()
        + ChanceAction(GameController game)
    }
    class GoTravelingCard{
        + GoTravelingCard()
        + ChanceAction(GameController game, BuildableBlock building)
    }
    class RipOffCard{
        + RipOffCard()
        + ChanceAction(GameController game)
    }


}

IPlayer <|.. Player : Implementation
namespace PlayerNamespace{
    class IPlayer{
    <<interface>>
        + GetName() : string
        + GetId() : int
    }
    class Player {
        _id : int
        _name : string
    }
}

GameController *-- Player : Compotition
GameController *-- PlayerData : Compotition
GameController *-- BaseBlock : Compotition
GameController *-- BuildableBlock : Compotition
GameController .. WinningCondition : Association

PlayerData *-- BaseBlock : Compotition
PlayerData *-- IDeffenseCard : Compotition
PlayerData .. PlayerStatus : Association
namespace Game{
    class GameController{
        - ~readonly~ _board : BaseBlock[32]
        - _players : Dictionary~Player.PlayerData~
        - _currentPlayer : Player
        - _dices : int[2]
        - _diceDoubleCount : int
        - _winner : IPlayer
        - _winnerStatus : WinningCondition
        - _onFinishTurn : Action

        + GameController(List~IPlayer~ players)
        + StartGame()
        + RollDice() : int
        - IsRollDiceDouble() : bool
        - GoToPrison()
        + PlayerMove(IPlayer player, int dice) : bool
        + PlayerAction(IPlayer player, BaseBlock block) : bool
        + NextTurn() : IPlayer
        + GetBoard() : BaseBlock[32]
        + GetCurrentPlayer() IPlayer
        + GetPlayers() : IEnumerable~IPlayer~
        + GetPlayer(int id) IPlayer
        + GetPlayerPosition(int id) : BaseBlock
        + GetPlayerBuildings(int id) : IEnumerable~BuildableBlock~
        + GetWinner() : IPlayer
        + GetWinnerStatus() : WinningCondition
        - CheckColorCompletion()
        - CheckLineCompletion()
        - CheckTourismCompletion()
        - CheckPlayerBankrupty()
    }

    class PlayerData{
        - _playerBalance : int
        - _totalAset : int
        - _turn : int
        - _playerStatus : PlayerStatus
        - _playerBuildings : List~BuildableBlock~ 
        - _playerPosition : BaseBlock
        - _playerPrisonCount : int
        - _deffenseCard : IDeffenseCard
    }
}

namespace Enum {
class BlockColor{
        <<enum>>
        Green
        Blue
        Yellow
        Red
        None
    }

    class BlockType{
        <<enum>>
        Start
        City
        Tourist
        Chance
        Prison
        Festival
        Traveling
        Tax
    }

    class BlockLine{
        <<enum>>
        first
        second
        third
        fourth
    }
    
    class BuildingEffect{
        <<enum>>
        Storm = 50
        Blackout = 0
        Festival = 200
    }

    class PropertyType{
        <<enum>>
        Land = 1
        Vila = 2
        Building = 3
        Hotel = 4
        Landmark = 5
    }

    class ChanceCardType{
        <<enum>>
        Attack
        Deffense
        Command
    }

    class PlayerStatus{
        <<enum>>
        Playing
        Winner
        Loser
        Bankrupt
    }

    class WinningCondition{
        <<enum>>
        ColorCompletion
        LineCompletion
        TourismCompletion
        Bankruptcy
    }
}

